### ISSUE TITLE
[Feature Request] Refresh config on a set interval

### ISSUE THREAD

**Issue by dclaverty** [adamkl/cloud-foundry-config-client#18]
I would like to set an option to refresh the config server on a set interval.  

```
interval(60) // get new config every 60 seconds
```
If unable to reach the config server, then log an error and keep the current config.

**Comment by adamkl** [comment]
Try out the latest [v1.2.0](https://www.npmjs.com/package/cloud-foundry-config-client/v/1.2.0).

I've added an additional `load` parameter for auto-refreshing the config.

Let me know if you run into any issues with it.
