### ISSUE TITLE
[Feature Request] Handle another authentication mechanism

### ISSUE THREAD

**Issue by dclaverty** [adamkl/cloud-foundry-config-client#19]
```
 "credentials": {
            "credhub-ref": "/c/p-spring-cloud-services/p-config-server/f5d64814-4986-496c-8396-fbfa8e6f2917/credentials-json"
          }
```

**Comment by adamkl** [comment]
I was looking into this, and it doesn't seem like any change needs to be made. That `credhub-ref` only appears when viewing the `VCAP_SERVICES` environment variable. At run time, that reference it replaced with the raw credentials, which is what the container sees. pivotal-cf/docs-spring-cloud-services#94

I'll confirm, but I'm expecting to close this with no change required.

**Comment by dclaverty** [comment]
Good news.  I can test again and confirm also.

**Comment by dclaverty** [comment]
I guess the issue is I need to figure out how to grab the runtime credentials if I want to connect locally.  Not a show stopper for me as I am good with using a local yml file.
