### ISSUE TITLE
Config client doesn't work if config has encrypted values

### ISSUE THREAD

**Issue by myamith** [adamkl/cloud-foundry-config-client#26]
our config yaml has encrypted values like 
`USERNAME:
  {cipher}c487bd3e71a0f068733520320c010c91765daf9bf92cb8365b958d08527`
`PASSWORD:
  {cipher}c8d51d633446af42c14e54003bb7dcae3ebcaddfabd4a164ec68c6cab0c`
however client fails to load such config files

**Comment by adamkl** [comment]
When you say it fails to load, do you mean it throws an error? Or does it load, but the values are blank? Or does it load, but the values are still encrypted?

This library performs the authentication handshake inside PCF before calling the config server, and it parses the resulting yaml file, but it doesn’t handle any sort of credential decryption.

**Comment by myamith** [comment]
I found the problem, not an issue with the client.
suppose to have {cipher} value in quotes since its yml and it worked 
`USERNAME: "{cipher}c487bd3e71a0f068733520320c010c91765daf9bf92cb8365b958d08527"`

Thanks
