### ISSUE TITLE
Update related to crudhub in config server

### ISSUE THREAD

**Issue by lnrajput** [adamkl/cloud-foundry-config-client#27]
Pivotal came with new credhub-ref for managing credentials of config server VCAP SERVICES. I am using this npm package in our applications and now Pivotal changed of crudhub require to update new p.config-server service which used crudhub-ref for credential mgmt. will our npm package work with change or we need to look into something else till updates comes?

"credentials": {
     "access_token_uri": "https://p-spring-cloud-services.uaa.sys.example.com/oauth/token",
     "client_id": "p-config-server-example-client-id",
     "client_secret": "EXAMPLE_SECRET",
     "uri": "https://config-c61e8f98-72d0-444d-abfc-2668ace3af9b.apps.example.com"
    }

"credentials": {
            "credhub-ref": "/c/p.spring-cloud-services-scs-service-broker/e9ca1323d-c312-4f57-88a4-aef0932423487f83/10e91f4c-e757-49da-b4d7-4137324294d7ab/credentials-json"
          },

**Comment by adamkl** [comment]
It shouldn't be a problem. See #19

**Comment by lnrajput** [comment]
> It shouldn't be a problem. See #19

Thanks Adam for quick response.
